name: Node.js CI
  # Get your key at https://platform.openai.com/account/api-keys
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  release:
    name: semantic-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: release
        run: |
          npm ci
          npx semantic-release --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
